development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: goran.mandinic@gmail.com
  :password: xxx
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: goran.mandinic@gmail.com
  :password: xxx
  :enable_starttls_auto: true